[default]
duration = "5m"
mode = "center"
sorting = "random"

[default.transition.stereo-viewer]

[any]
path = "/home/athereo/Pictures/Wallpapers"

# [eDP-1]
# path = "/home/athereo/Pictures/Wallpapers"


